#!/bin/bash
set -e
tag=r00046.1
fullver=${tag##r}
ver=${fullver%.*}
label=MSM8952.LA.1.0.1-${ver}-STD.PROD-1

echo check-in "${tag} (${label})..."
echo Fetch...
./fetchall.sh
echo "Check-out ${tag}"
(cd source; git reset --hard; git clean -xdf; git checkout ${tag})
(cd prebuilt; git reset --hard; git clean -xdf; git checkout ${tag})
(cd hap; git reset --hard; git clean -xdf; git checkout ${tag})
#(cd xtra_tz_src; git reset --hard; git clean -xdf; git checkout ${tag})
#(cd lte; git reset --hard; git clean -xdf; git checkout ${tag})
cp source/about.html source/common/
cp source/contents*.xml source/common/
if [ -f source/LINUX/android/vendor/qcom/proprietary/vendorsetup.sh ]; then
    cp source/LINUX/android/vendor/qcom/proprietary/vendorsetup.sh source/LINUX/android/vendor/qcom/proprietary/common
fi

#echo "REMOVING clang-rs -- empty dir!"
#rm -rf source/LINUX/android/vendor/qcom/proprietary/clang-rs

# produce the build id file.
echo "### DO NOT MODIFY - MOTOROLA AUTO-GENERATED!!!" > source/LINUX/android/vendor/qcom/proprietary/prebuilt_HY11/prebuilt.mk
echo "### This file is automatically regenerated by Motorola" >> source/LINUX/android/vendor/qcom/proprietary/prebuilt_HY11/prebuilt.mk
echo "### each QCOM merge.  All modifications will be lost." >> source/LINUX/android/vendor/qcom/proprietary/prebuilt_HY11/prebuilt.mk
echo "" >> source/LINUX/android/vendor/qcom/proprietary/prebuilt_HY11/prebuilt.mk
echo "# QCOM AP build ID" >> source/LINUX/android/vendor/qcom/proprietary/prebuilt_HY11/prebuilt.mk
echo "ADDITIONAL_BUILD_PROPERTIES += \\"  >> source/LINUX/android/vendor/qcom/proprietary/prebuilt_HY11/prebuilt.mk
echo "    ro.build.version.qcom=${label} " >> source/LINUX/android/vendor/qcom/proprietary/prebuilt_HY11/prebuilt.mk

python build_support/bin/qc_checkin.py checkin -c build_support/bin/8952.cfg -v${ver} -l"${label} (${tag})" $@

# push it
#python build_support/bin/qc_checkin.py push -c build_support/bin/852.cfg $@
